name: Continous Integration

on:
  push:
    branches: [ "main" ]

env:
  SOURCE_DIR: src

jobs:
  build:
    runs-on: windows2022
    steps:
    - uses: actions/checkout@v2
    
    - name: Restore Packages
      working-directory: ${{ env.SOURCE_DIR }}
      run: dotnet restore
    
    - name: Build Plastic
      working-directory: ${{ env.SOURCE_DIR }}
      run: dotnet build -c Release --no-restore
      
    - name: Test
      working-directory: ${{ env.SOURCE_DIR }}
      run: dotnet test -c Release
