name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  SOURCE_DIR: src

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Restore Packages
      working-directory: ${{ env.SOURCE_DIR }}
      run: dotnet restore
        
    - name: Build Plastic
      working-directory: ${{ env.SOURCE_DIR }}
      run: dotnet build -c Release --no-restore
      
    - name: Test 
      working-directory: ${{ env.SOURCE_DIR }}
      run: dotnet test -c Release
      
    - name: Publish Package to Nuget.org
      run: dotnet nuget push **/PlasticCommand.*.nupkg --api-key ${{ secrets.NugetApiKey }} --source "nuget.org" --skip-duplicate --no-symbols
